export {LandingPage} from "./LandingPage/LandingPage"
export {Login} from "./Auth/Login"
export {Signup} from "./Auth/Signup"
export {Logout} from "./Auth/Logout"
export {Home} from "./Home/Home"
export {Labels} from "./Labels/Labels"
export {Trash} from "./Trash/Trash"
export {Archive} from "./Archive/Archive"